# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CsWDZXU0R9I2kdIZHWAGJoaVMkm8j1e_
"""

!pip install streamlit
!pip install tensorflow
!pip install pillow
import streamlit as st
import numpy as np
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
from PIL import Image

# Load model
model = load_model("pneumonia_efficientnetb0.h5")

# Title
st.title("🩺 Pneumonia Detection from Chest X-rays")
st.markdown("Upload a chest X-ray image and let the model detect if Pneumonia is present.")

# File uploader
uploaded_file = st.file_uploader("Upload Chest X-ray Image", type=["jpg", "png", "jpeg"])

# Predict function
def predict(img_path):
    img = image.load_img(img_path, target_size=(224, 224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0) / 255.0
    prediction = model.predict(img_array)[0][0]
    return "Pneumonia" if prediction > 0.5 else "Normal", prediction

# Prediction section
if uploaded_file is not None:
    img = Image.open(uploaded_file)
    st.image(img, caption="Uploaded Image", use_column_width=True)

    # Save and predict
    with open("temp.jpg", "wb") as f:
        f.write(uploaded_file.getbuffer())

    label, confidence = predict("temp.jpg")
    st.markdown(f"### Prediction: **{label}**")
    st.markdown(f"**Confidence Score**: {confidence:.2f}")

